apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com-pod
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: wardviaene/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
      
---
apiVersion: v1
kind: Service
metadata: 
  name: nodehelloworld-service
spec:
  ports:
  - port: 31001 #is the port on which service is exposed within the cluster
    nodePort: 31001
    targetPort: nodejs-port #is the port on which traffice is forwarded to the pods that match the service's selector. 
    #It is the port on which the application in the pods is listening
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort

