apiVersion: v1
kind: Pod
metadata:
  name: helloworld-pod
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: wardviaene/k8s-demo
    ports:
    - name: nodejs-port
      containerPort: 3000
      volumeMounts:
      - mountPath: /host-path
        name: host-volumes
  volumes:
  - name: host-volume
    hostPath:
      path: /volumes